### ISSUE TITLE
Should File.separator be used instead of '/' in GenericAssetFile to make it OS agnostic?

### ISSUE THREAD

**Issue by dmahapatro** [bertramdev/asset-pipeline-core#10]
While trying to fix failing tests in `angular-asset-pipeline-plugin` by @craigburke in Windows platform, I came across `GenericAssetFile` used in the plugin. 

`/` is used as path separator in this class. This was causing tests to fail in windows because `\` being the file separator in Windows. 

Should it (`GenericAssetFile`) be modified to use `File.separator` in order to make the implementation OS agnostic? I found out this was the reason tests we failing for angular-asset-pipeline plugin. 

Here is the [related line for failing test](https://github.com/craigburke/angular-template-asset-pipeline/blob/f2c48a2564f100e45666db7b205f5a89f672f62e/core/src/main/groovy/com/craigburke/angular/TemplateProcessorUtil.groovy#L35) and here is the [PR submitted to fix it by bypassing call to `GenericAssetFile`](https://github.com/craigburke/angular-template-asset-pipeline/blob/master/core%2Fsrc%2Fmain%2Fgroovy%2Fcom%2Fcraigburke%2Fangular%2FTemplateProcessorUtil.groovy#L47)

**Comment by davydotcom** [comment]
I am using AP in windows successfully atm not sure what is being referred to here. Please bare in mind that the AP paths are kept in '/' relative path structure across all platforms and the resolvers are smart enough to translate back to OS Specific paths

**Comment by dmahapatro** [comment]
Will test this along with angularjs-asset-pipeline and see if I face any issue. Thanks for responding.

**Comment by dmahapatro** [comment]
BTW, I was indicating [this line](https://github.com/bertramdev/asset-pipeline-core/blob/56aa95efff57c96e3c062e629320dbeba0e1e951/asset-pipeline-core/src/main/groovy/asset/pipeline/GenericAssetFile.groovy#L48) in particular which I think was error prone while fixing the ATAP plugin.

**Comment by davydotcom** [comment]
That path value should always be '/' separator. it should be the converted path

**Comment by davydotcom** [comment]
Basically i try to get rid of the os specific path separator at the resolver level so I don't have to account for it on up the chain.

**Comment by craigburke** [comment]
@davydotcom I didn't know that. Obviously my tests are wrong then and I'll have to revisit the Window issue again in my project.

**Comment by dmahapatro** [comment]
I don't think you need to anymore @craigburke, but I will try to use `GenericAssetFile` and run the test immediately.

**Comment by dmahapatro** [comment]
@craigburke created a [new issue](https://github.com/craigburke/angular-template-asset-pipeline/issues/16) in ATAP to trace what is going on.

**Comment by craigburke** [comment]
I think you can probably close this. I've confirmed it was simply an incorrect assumption in my tests related to the file path.
