### ISSUE TITLE
Propose ability to mix CDN resources with local

### ISSUE THREAD

**Issue by theaspect** [bertramdev/asset-pipeline-core#11]
The easiest way to achieve this will be call `grails.assets.url` closure and if it return null fallback to default mechanism

**Comment by davydotcom** [comment]
that is a good idea if grails.assets.url closure is null fallback. i can add that in. This is actually grails specific so it goes in the [asset-pipeline](/bertramdev/asset-pipeline) repo.

**Comment by davydotcom** [comment]
staged for AP grails adapter
