### ISSUE TITLE
Proposal: raise event after postprocess finished

### ISSUE THREAD

**Issue by theaspect** [bertramdev/asset-pipeline-core#12]
You raising here https://github.com/bertramdev/asset-pipeline-core/blob/master/asset-pipeline-core/src/main/groovy/asset/pipeline/AssetCompiler.groovy#L226 common event. Better raise distinct event e.g. "AssetsProcessed" so we can hook and do custom post-post-process.

It even can looks like: 
grails.war.resources = { stagingDir ->
    whatever(gant: task, we: want)
}

**Comment by davydotcom** [comment]
exists in the grails adaptation for GANT. you can find it here: https://github.com/bertramdev/asset-pipeline/blob/master/scripts/_AssetCompile.groovy#L79
