### ISSUE TITLE
Asset pipeline 2.5.0 assetCompile task fails to use processors with a gradle application

### ISSUE THREAD

**Issue by anthofo** [bertramdev/asset-pipeline-core#36]
Hi,

I have a very basic application available here : https://github.com/anthofo/asset-pipeline-bug
This app uses Spring boot + gradle. The app uses Typescript, so I developped a TypeScript processor for asset pipeline.
I'm also using the spring boot asset pipeline plugin.

The problem is that my TypeScriptProcessor is correctly called by the spring boot plugin when I run my app, and the Typescript is compiled to javascript.

But, when I launch the assetCompile task, the TypeScriptProcessor is not called at all and my ts is interpreted like js, which produces an error : 

```
:assetCompile
Processing File 1 of 2 - application.js
Uglifying File 1 of 2 - application
application.unminified.js:2: ERROR - Parse error. ',' expected
    constructor(public greeting: string) { }
                       ^
Compressing File 1 of 2 - application
Processing File 2 of 2 - testts.ts
Compressing File 2 of 2 - testts
```

I also tried to use existing processors such as CoffeeScript and I have exactly the same problem.

So for now, I'm able to use asset pipeline at runtime on dev mode, but I cannot produce a jar :s

**Comment by davydotcom** [comment]
did you create a plugin and include it in both the build script and the dependencies list?
